### ISSUE TITLE
Allow patients to come in through the ambulance entrance

### ISSUE THREAD

**Issue by bricksphd** [crowdedjs/examples#62]
Sev 1 patients often arrive at the ambulance drop off. We need to handle this situation.

**Comment by rnarducci** [comment]
Unsure how deep to originally make this feature. First thought is we will need a behavior tree for ambulance people that will be included with the ESI1 patient on the json file for arrivals to take care of that person.

**Comment by rnarducci** [comment]
How should the emergency patients be entered into the computer? Which agent should do it and when should they enter them?

**Comment by bricksphd** [comment]
I don't know. I think if they really have a severe condition, they would be entered by the nurse or doctor who's in communication with the ambulance team.
