### ISSUE TITLE
Convert to distanceToSquared and lengthSquared

### ISSUE THREAD

**Issue by bricksphd** [crowdedjs/examples#69]
See https://github.com/crowdedjs/math/issues/1

In almost all places where we use distanceTo and length, we could use distanceToSquared and lengthSquared. Times include when we compared based on distance (x^2>y^2=>x>y) such as this updated line:

https://github.com/bricksphd/trash.recast-detour/blob/e9100c3f542e19f75c0314b82866d688d1d43157/src/behavior/look-for-arriving-patient.js#L28

Or when we compare to  a constant such as this updated line:

https://github.com/bricksphd/trash.recast-detour/blob/e9100c3f542e19f75c0314b82866d688d1d43157/src/behavior/look-for-arriving-patient.js#L30

The only time we really need to use length instead of lengthSquared is when we normalize, so we need to keep it in for that.

**Comment by rnarducci** [comment]
Changed all the distanceTo and length lines to Squared. Compensated in the comparisons for this, and the simulation seems to be running without issue. Hopefully it stays that way and improves long term performance a bit!
